name: First workflow in React
on: 
  push: 
    branches:  
      - main
jobs: 
  build: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.9.1
      - run: |
          node -v
          npm -v
          npm install
          npm run build
